# Generated by Django 3.2.4 on 2021-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=20)),
                ('Product_Category', models.CharField(max_length=20)),
                ('Product_Description', models.CharField(max_length=100)),
                ('Product_Image', models.ImageField(upload_to='img/ProductImages')),
            ],
        ),
    ]
