# Generated by Django 3.2.4 on 2021-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210719_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Description',
            field=models.CharField(max_length=1000),
        ),
    ]
